sudo: false
language: python
python:
  - "2.7"
install:
    - ./install.sh miniconda
    - export PATH=$PWD/miniconda/bin:$PATH
before_script:
    - 'echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"'
    - '.travis/master.sh'
    - '.travis/develop.sh'
script:
    - nosetests -v test_code.py
