sudo: false
language: python
python:
  - "2.7"
install:
    - ./install.sh miniconda
    - export PATH=$PWD/miniconda/bin:$PATH
script:
    - '[ "$TRAVIS_BRANCH" == "master" ] && .travis/in_commit.sh CHANGELOG.rst'
    - '[ "$TRAVIS_BRANCH" == "develop" ] && .travis/in_commit.sh CHANGELOG.rst docs'
    - nosetests test_code.py
