sudo: false
language: python
python:
  - "2.7"
install:
    - ./install.sh miniconda
    - export PATH=$PWD/miniconda/bin:$PATH
before_script:
    - 'echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"'
    - '[ "$TRAVIS_BRANCH" = "master" ] && .travis/master.sh'
    - '[ "$TRAVIS_BRANCH" = "develop" ] && .travis/develop.sh'
script:
    - nosetests -v test_code.py
