sudo: false
language: python
python:
  - "2.7"
install:
    - ./install.sh miniconda
    - export PATH=$PWD/miniconda/bin:$PATH
before_script:
    - 'echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"'
    - 'echo "TRAVIS_TAG: $TRAVIS_TAG"'
    - 'echo "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"'
    - '.travis/master.sh'
    - '.travis/develop.sh'
    - '.travis/tag.sh'
script:
    - nosetests -v tests
after_success:
    - .travis/push_release_tag.sh
